server:
  port: ${port:8100}
  session: 
    timeout: 0

spring:
  application:
    name: Sample #current service name to be used by the eureka server

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG